### ISSUE TITLE
Consider replacing object return types with nparray

### ISSUE THREAD

**Issue by Happypig375** [Quansight-Labs/numpy.net#22]
This way, we can chain numpy operations better. To extract values we can still cast.

**Comment by KevinBaselinesw** [comment]
I don't understand this comment.  Can you provide an example of when I am returning an object?

I think most of the functions return ndarray objects.  In a scenario where python is returning a scalar value instead of an array,  I provide ability to cast the array to the specified type to get make it equivalent with python.

C# requires strict definitions for return values.  In other words, the same function can't return an ndarray sometimes and a scalar value a different time like python can.  So, I always return an ndarray even if there is just one element.  There is an easy cast to get that first element.

**Comment by Happypig375** [comment]
object np.min(object)
object np.max(object)
object ndarray.this[object]

For example. These should return ndarray.

**Comment by KevinBaselinesw** [comment]
I don't understand your example.  In the unit tests below, I tried to create some examples in both languages.  The 'c' line does not compile in either language but 'a' and 'b' are the same result.  Can you provide a more complete example?

Python unit test

  ```
 def test_HadrianTang_13(self):

       objecta = 9.234
       objectb = 33

       a = np.min(objecta)
       b = np.max(objectb)
       #c =  ndarray.this[objectb]

       print(a)
       print(b)
       #print(c)
```

C# unit test


  ```
      [TestMethod]
        public void test_HadrianTang_13()
        {
            var objecta = 9.234;
            var objectb = 33;

            var a = np.min(objecta);
            var b = np.max(objectb);
           // var c = ndarray.this[object];

            return;
        }
```

**Comment by Happypig375** [comment]
Oh they are method signatures.

**Comment by Happypig375** [comment]
The signature should have a return type of ndarray instead of object.

**Comment by KevinBaselinesw** [comment]
Please use amax and amin to get the return values as ndarray objects.

This is one of those weird cases where python can return either an ndarray or scalar value.  Since I can't do that, I made np.max and np.min return the scalar and np.amax and np.amin return the array.

**Comment by Happypig375** [comment]
But scalars can be represented using 0D arrays right?

**Comment by Happypig375** [comment]
What about indexing?

**Comment by KevinBaselinesw** [comment]
Here is a simple example of indexing that returns an ndarray class.   This will not compile because the 'set' operations must also be ndarray.  It is not a problem returning an ndarray.  It is a huge problem trying to set values to the index.  I don't think we want to force everyone to convert every set operation to an ndarray.
 ```
   public partial class ndarrayXX
        {
            public ndarrayXX this[int index]
            {
                get
                {
                    return null;
                }
                set
                {

                }
            }
        }

        [TestMethod]
        public void test_HadrianTang_14()
        {
            ndarrayXX HadrianTang = new ndarrayXX();

            ndarrayXX a = HadrianTang[3];

            HadrianTang[3] = 2;

            return;
        }
```

**Comment by Happypig375** [comment]
thanks for explaining!
